server:
  port: 9081

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: "%msg%n"
  level:
    root: WARN
    com.example.demo.util.FinalCheckUtil: DEBUG
    com.example.demo.controller.CheckerController: DEBUG
